<?php return array(
    'title' => __('Belize', 'woocommerce'),
    'country' => 'BZ',
    'items' => array(

        'BZ10'  => __('Belize – Ambergris Caye', 'woo-locations'),
        'BZ20'  => __('Belize – Belize City', 'woo-locations'),
        'BZ30'  => __('Belize – Caye Caulker', 'woo-locations'),
        'BZ40'  => __('Belize – Ladyville', 'woo-locations'),
        'BZ50'  => __('Belize – San Pedro', 'woo-locations'),
        'BZ60'  => __('Belize – Sand Hill', 'woo-locations'),

        'CY10'  => __('Cayo – Belmopan', 'woo-locations'),
        'CY20'  => __('Cayo – Benque Viejo Del Carmen', 'woo-locations'),
        'CY30'  => __('Cayo – Bullet Tree Falls', 'woo-locations'),
        'CY40'  => __('Cayo – San Ignacio', 'woo-locations'),
        'CY50'  => __('Cayo – Santa Elena', 'woo-locations'),
        'CY'    => __('Cayo – Other', 'woo-locations'),

        'CZ10'  => __('Corozal – Corozal Town', 'woo-locations'),
        'CZ20'  => __('Corozal – Altamira', 'woo-locations'),
        'CZ30'  => __('Corozal – Buena Vista', 'woo-locations'),
        'CZ40'  => __('Corozal – Calcutta', 'woo-locations'),
        'CZ50'  => __('Corozal – Caledonia', 'woo-locations'),
        'CZ60'  => __('Corozal – Carolina', 'woo-locations'),
        'CZ70'  => __('Corozal – Chan Chen', 'woo-locations'),
        'CZ80'  => __('Corozal – Chunox', 'woo-locations'),
        'CZ90'  => __('Corozal – Concepcion', 'woo-locations'),
        'CZ100' => __('Corozal – Consejo', 'woo-locations'),
        'CZ110' => __('Corozal – Copper Bank', 'woo-locations'),
        'CZ120' => __('Corozal – Cristo Rey', 'woo-locations'),
        'CZ130' => __('Corozal – Estrella', 'woo-locations'),
        'CZ140' => __('Corozal – Libertad', 'woo-locations'),
        'CZ150' => __('Corozal – Little Belize', 'woo-locations'),
        'CZ160' => __('Corozal – Louisville', 'woo-locations'),
        'CZ170' => __('Corozal – Paraiso', 'woo-locations'),
        'CZ180' => __('Corozal – Patchakán', 'woo-locations'),
        'CZ190' => __('Corozal – Progresso', 'woo-locations'),
        'CZ200' => __('Corozal – Ranchito', 'woo-locations'),
        'CZ210' => __('Corozal – San Andrés', 'woo-locations'),
        'CZ220' => __('Corozal – San Antonio', 'woo-locations'),
        'CZ230' => __('Corozal – San Joaquin', 'woo-locations'),
        'CZ240' => __('Corozal – San Narciso', 'woo-locations'),
        'CZ250' => __('Corozal – San Pablo', 'woo-locations'),
        'CZ260' => __('Corozal – San Pedro', 'woo-locations'),
        'CZ270' => __('Corozal – San Román', 'woo-locations'),
        'CZ280' => __('Corozal – San Victor', 'woo-locations'),
        'CZ290' => __('Corozal – Santa Clara', 'woo-locations'),
        'CZ300' => __('Corozal – Santa Elena', 'woo-locations'),
        'CZ310' => __('Corozal – Sarteneja', 'woo-locations'),
        'CZ320' => __('Corozal – Xaibe', 'woo-locations'),
        'CZ330' => __('Corozal – Yo Chen', 'woo-locations'),

        'SC10'  => __('Stann Creek – Dangriga', 'woo-locations'),
        'SC20'  => __('Stann Creek – Placencia', 'woo-locations'),
        'SC'    => __('Stann Creek – Other', 'woo-locations'),

        'TOL10' => __('Toledo – Barranco', 'woo-locations'),
        'TOL20' => __('Toledo – Monkey River Town', 'woo-locations'),
        'TOL30' => __('Toledo – Punta Gorda', 'woo-locations'),
        'TOL40' => __('Toledo – San Antonio', 'woo-locations'),
        'TOL'   => __('Toledo – Other', 'woo-locations'),
    ),
);