<?php return array(
    'obsolete_since' => '6.1.0',
    'title' => __('Ecuador', 'woocommerce'),
    'country' => 'EC',
    'items' => array(
        'EC01' => 'Azuay',
        'EC02' => 'Bolívar',
        'EC03' => 'Cañar',
        'EC04' => 'Carchi',
        'EC05' => 'Chimborazo',
        'EC06' => 'Cotopaxi',
        'EC07' => 'El Oro',
        'EC08' => 'Esmeraldas',
        'EC09' => 'Galápagos',
        'EC10' => 'Guayas',
        'EC11' => 'Imbabura',
        'EC12' => 'Loja',
        'EC13' => 'Los Ríos',
        'EC14' => 'Manabí',
        'EC15' => 'Morona Santiago',
        'EC16' => 'Napo',
        'EC17' => 'Orellana',
        'EC18' => 'Pastaza',
        'EC19' => 'Pichincha',
        'EC20' => 'Santa Elena',
        'EC21' => 'Santo Domingo de los',
        'EC22' => 'Sucumbíos',
        'EC23' => 'Tungurahua',
        'EC24' => 'Zamora-Chinchipe',
    ),
);