<?php return array(
    'title' => __('Portugal', 'woocommerce'),
    'country' => 'PT',
    'items' => array(
        'AC' => 'Azores',
        'AV' => 'Aveiro',
        'BJ' => 'Beja',
        'BR' => 'Braga',
        'BG' => 'Bragança',
        'CB' => 'Castelo Branco',
        'CM' => 'Coimbra',
        'EV' => 'Évora',
        'FR' => 'Faro',
        'GD' => 'Guarda',
        'LR' => 'Leiria',
        'LS' => 'Lisbon',
        'MD' => 'Madeira',
        'PR' => 'Portalegre',
        'PT' => 'Oporto',
        'ST' => 'Santarém',
        'SB' => 'Setúbal',
        'VC' => 'Viana do Castelo',
        'VR' => 'Vila Real',
        'VS' => 'Viseu',
    ),
);